import {FormEvent,useEffect,useState} from "react";
import api from "../services/api";
import {appAlert} from "../components/AppDialog";

type Row={id:string;date:string;kind:"earning"|"deduction";reason:string;route?:string|null;amount:number};
type Period={id:number;period_start:string;period_end:string;release_date:string;status:string;version:number;snapshot_hash:string;snapshot:{driver:{name:string;document?:string;employment_type:string};rows:Row[];earnings:number;deductions:number;net:number};contest?:{scope:string;item_id?:string;reason:string}|null;accepted_at?:string|null;signature_name?:string|null;payable_id?:number|null};
const money=(value:number)=>value.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const statusLabel:Record<string,string>={released:"Disponível para conferência",contested:"Em análise pelo Financeiro",accepted:"Aceito e enviado para pagamento"};

export default function DriverStatementPortal(){
  const [periods,setPeriods]=useState<Period[]>([]),[selected,setSelected]=useState<Period|null>(null),[accepting,setAccepting]=useState(false),[contesting,setContesting]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const [signature,setSignature]=useState({signature_name:"",document:"",declaration_accepted:false});
  const [contest,setContest]=useState({scope:"total",item_id:"",reason:""});
  const load=async()=>{const {data}=await api.get<Period[]>("/erp/driver-statement-periods/my");setPeriods(data);setSelected(current=>data.find(row=>row.id===current?.id)||data[0]||null)};
  useEffect(()=>{void load().catch((e)=>setError(e?.response?.data?.detail||"Não foi possível carregar seus extratos."))},[]);
  const available=selected&&selected.status==="released"&&new Date(`${selected.release_date}T12:00:00`)<=new Date();
  async function accept(event:FormEvent){event.preventDefault();if(!selected)return;setBusy(true);setError("");try{const {data}=await api.post(`/erp/driver-statement-periods/${selected.id}/accept`,signature);setAccepting(false);await load();await appAlert(`Aceite registrado. Conta a pagar #${data.payable_id} criada. Guarde o hash ${data.snapshot_hash}.`,{title:"Assinatura eletrônica concluída"})}catch(e:any){setError(e?.response?.data?.detail||"Não foi possível concluir o aceite.")}finally{setBusy(false)}}
  async function submitContest(event:FormEvent){event.preventDefault();if(!selected)return;setBusy(true);setError("");try{const {data}=await api.post(`/erp/driver-statement-periods/${selected.id}/contest`,{...contest,item_id:contest.scope==="item"?contest.item_id:null});setContesting(false);await load();await appAlert(`Contestação enviada ao Financeiro como tarefa prioritária #${data.task_id}.`,{title:"Contestação registrada"})}catch(e:any){setError(e?.response?.data?.detail||"Não foi possível registrar a contestação.")}finally{setBusy(false)}}
  return <div className="page-card"><div className="page-header"><div><h2>Meus ganhos e descontos</h2><p className="page-subtitle">Confira cada fechamento antes de autorizar o pagamento.</p></div></div>
    {error&&<p className="modal-error">{error}</p>}
    <div className="card-panel statement-filters"><label className="field"><span>Período</span><select className="input" value={selected?.id||""} onChange={event=>setSelected(periods.find(row=>row.id===Number(event.target.value))||null)}><option value="">Selecione</option>{periods.map(period=><option key={period.id} value={period.id}>{period.period_start} a {period.period_end} · {statusLabel[period.status]||period.status}</option>)}</select></label></div>
    {!selected?<div className="empty-state">Nenhum extrato foi liberado para seu usuário.</div>:<>
      <div className="statement-summary"><article><span>Ganhos</span><strong className="positive">{money(selected.snapshot.earnings)}</strong></article><article><span>Descontos</span><strong className="negative">{money(selected.snapshot.deductions)}</strong></article><article><span>Líquido</span><strong>{money(selected.snapshot.net)}</strong></article></div>
      <p><span className={`stock-badge ${selected.status==="accepted"?"ok":selected.status==="contested"?"warning":""}`}>{statusLabel[selected.status]||selected.status}</span> · versão {selected.version} · liberação em {new Date(`${selected.release_date}T12:00:00`).toLocaleDateString("pt-BR")}</p>
      {selected.contest&&<p className="modal-error"><strong>Contestação:</strong> {selected.contest.reason}</p>}
      <div className="table-scroll"><table className="data-table"><thead><tr><th>Data</th><th>Tipo</th><th>Motivo</th><th>Rota</th><th>Valor</th></tr></thead><tbody>{selected.snapshot.rows.map(row=><tr key={row.id}><td>{row.date}</td><td>{row.kind==="earning"?"Ganho":"Desconto"}</td><td>{row.reason}</td><td>{row.route||"-"}</td><td className={row.kind==="earning"?"positive":"negative"}>{money(row.amount)}</td></tr>)}</tbody></table></div>
      {available&&<div className="modal-actions"><button className="btn-primary" onClick={()=>setAccepting(true)}>Aceitar e assinar</button><button className="btn-ghost" onClick={()=>setContesting(true)}>Recusar ou contestar</button></div>}
      {selected.status==="accepted"&&<p>Assinado por <strong>{selected.signature_name}</strong> em {selected.accepted_at?new Date(selected.accepted_at).toLocaleString("pt-BR"):"-"}. Conta a pagar #{selected.payable_id}.<br/><small>Hash do documento: {selected.snapshot_hash}</small></p>}
    </>}
    {accepting&&selected&&<div className="modal-backdrop" onClick={()=>setAccepting(false)}><form className="modal-card" onSubmit={accept} onClick={e=>e.stopPropagation()}><h3>Assinatura eletrônica do extrato</h3><p>Período {selected.period_start} a {selected.period_end} · líquido {money(selected.snapshot.net)}</p><div className="form-grid"><label className="field"><span>Nome completo</span><input className="input" required minLength={3} value={signature.signature_name} onChange={e=>setSignature({...signature,signature_name:e.target.value})}/></label><label className="field"><span>CPF/documento</span><input className="input" required minLength={5} value={signature.document} onChange={e=>setSignature({...signature,document:e.target.value})}/></label></div><label className="field"><span><input type="checkbox" required checked={signature.declaration_accepted} onChange={e=>setSignature({...signature,declaration_accepted:e.target.checked})}/> Declaro que conferi o extrato, reconheço os itens e valores apresentados e aceito o valor líquido para pagamento.</span></label><div className="modal-actions"><button className="btn-primary" disabled={busy}>Assinar e aceitar</button><button type="button" className="btn-ghost" onClick={()=>setAccepting(false)}>Cancelar</button></div></form></div>}
    {contesting&&selected&&<div className="modal-backdrop" onClick={()=>setContesting(false)}><form className="modal-card" onSubmit={submitContest} onClick={e=>e.stopPropagation()}><h3>Contestar extrato</h3><div className="form-grid"><label className="field"><span>Escopo</span><select className="input" value={contest.scope} onChange={e=>setContest({...contest,scope:e.target.value,item_id:""})}><option value="total">Valor total</option><option value="item">Um item específico</option></select></label>{contest.scope==="item"&&<label className="field"><span>Item</span><select className="input" required value={contest.item_id} onChange={e=>setContest({...contest,item_id:e.target.value})}><option value="">Selecione</option>{selected.snapshot.rows.map(row=><option key={row.id} value={row.id}>{row.date} · {row.reason} · {money(row.amount)}</option>)}</select></label>}</div><label className="field"><span>Explique a divergência</span><textarea className="input" required minLength={10} rows={5} value={contest.reason} onChange={e=>setContest({...contest,reason:e.target.value})}/></label><div className="modal-actions"><button className="btn-primary" disabled={busy}>Enviar contestação prioritária</button><button type="button" className="btn-ghost" onClick={()=>setContesting(false)}>Cancelar</button></div></form></div>}
  </div>;
}
