import {useEffect,useMemo,useState} from "react";
import api from "../services/api";
import {useAuth} from "../context/AuthContext";

type Row={id:number;code:string;name:string;account_type:string;nature:string;accepts_entries:boolean;opening:number;debit:number;credit:number;balance:number};
type Trial={start:string;end:string;rows:Row[];total_debit:number;total_credit:number;difference:number;balanced:boolean;closed:boolean};
type Tax={id:number;name:string;tax_code:string;rate_percent:number;effective_from:string;effective_to?:string|null;legal_basis?:string|null;source_url?:string|null;active:boolean};
type Ledger={account:{id:number;code:string;name:string;nature:string};rows:Array<{entry_id:number;date:string;memo:string;source_type:string;source_id:number;debit:number;credit:number;balance:number;tax_code?:string|null;tax_rate?:number|null}>};
const iso=(date:Date)=>date.toISOString().slice(0,10);const now=new Date();const monthStart=iso(new Date(now.getFullYear(),now.getMonth(),1));const monthEnd=iso(new Date(now.getFullYear(),now.getMonth()+1,0));const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);

export default function Financeiro(){
 const {hasPermission}=useAuth(),canManage=hasPermission("finance.accounts.manage","gestor_financeiro");
 const [tab,setTab]=useState("trial"),[start,setStart]=useState(monthStart),[end,setEnd]=useState(monthEnd),[data,setData]=useState<Trial|null>(null),[taxes,setTaxes]=useState<Tax[]>([]),[ledger,setLedger]=useState<Ledger|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[taxOpen,setTaxOpen]=useState(false),[confirmAction,setConfirmAction]=useState<{kind:"close"}|{kind:"tax";tax:Tax}|null>(null),[actionBusy,setActionBusy]=useState(false),[taxForm,setTaxForm]=useState({name:"",tax_code:"",rate_percent:"",effective_from:iso(now),effective_to:"",legal_basis:"",source_url:""});
 const load=()=>Promise.all([api.get<Trial>("/accounting/trial-balance",{params:{start,end}}),api.get<Tax[]>("/accounting/tax-rules")]).then(([trial,tax])=>{setData(trial.data);setTaxes(tax.data);setError("")}).catch(e=>setError(e?.response?.data?.detail||"Não foi possível carregar a contabilidade."));
 useEffect(()=>{load()},[start,end]);
 const activeRows=useMemo(()=>data?.rows.filter(row=>row.opening||row.debit||row.credit||row.balance||!row.accepts_entries)||[],[data]);
 async function openLedger(row:Row){if(!row.accepts_entries)return;const {data}=await api.get<Ledger>("/accounting/ledger",{params:{account_id:row.id,start,end}});setLedger(data);setTab("ledger")}
 async function saveTax(e:React.FormEvent){e.preventDefault();try{await api.post("/accounting/tax-rules",{...taxForm,rate_percent:Number(taxForm.rate_percent),effective_to:taxForm.effective_to||null,applies_to:"revenue",debit_account_code:"6.1.01",credit_account_code:"2.2.01"});setTaxOpen(false);load()}catch(err:any){setError(err?.response?.data?.detail||"Não foi possível salvar a regra tributária.")}}
 function activateTax(tax:Tax){setError("");setNotice("");setConfirmAction({kind:"tax",tax})}
 function closePeriod(){setError("");setNotice("");setConfirmAction({kind:"close"})}
 async function confirmOperation(){if(!confirmAction)return;setActionBusy(true);setError("");try{if(confirmAction.kind==="close"){await api.post("/accounting/periods/close",{start_date:start,end_date:end,cadence:periodCadence(start,end)});setNotice(`Período de ${formatDate(start)} a ${formatDate(end)} fechado com sucesso.`)}else{await api.post(`/accounting/tax-rules/${confirmAction.tax.id}/activate`);setNotice(`Vigência ${confirmAction.tax.tax_code} ativada com sucesso.`)}setConfirmAction(null);await load()}catch(e:any){setError(e?.response?.data?.detail||`Não foi possível ${confirmAction.kind==="close"?"fechar o período":"ativar a vigência tributária"}.`)}finally{setActionBusy(false)}}
 function exportCsv(){if(!data)return;const lines=[["Código","Conta","Saldo anterior","Débito","Crédito","Saldo atual"],...data.rows.map(r=>[r.code,r.name,r.opening,r.debit,r.credit,r.balance])];const blob=new Blob([lines.map(r=>r.join(";")).join("\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`balancete-${start}-${end}.csv`;a.click();URL.revokeObjectURL(url)}
 return <div className="accounting-page"><div className="page-header"><div><h2>Balancete contábil</h2><p className="page-subtitle">Partidas dobradas, razonetes, tributos por vigência e fechamento contábil.</p></div><div className="accounting-actions"><button className="btn-ghost" onClick={exportCsv}>Exportar contabilidade</button>{canManage&&!data?.closed&&<button className="btn-primary" disabled={!data?.balanced} onClick={closePeriod}>Fechar período</button>}</div></div>{error&&<div className="accounting-feedback is-error"><strong>Não foi possível concluir</strong><span>{error}</span><button type="button" onClick={()=>setError("")} aria-label="Fechar">×</button></div>}{notice&&<div className="accounting-feedback is-success"><strong>Operação concluída</strong><span>{notice}</span><button type="button" onClick={()=>setNotice("")} aria-label="Fechar">×</button></div>}
 <section className="card-panel accounting-period"><label className="field"><span>Data inicial</span><input className="input" type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="field"><span>Data final</span><input className="input" type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><span className={`stock-badge ${data?.closed?"warning":data?.balanced?"ok":"danger"}`}>{data?.closed?"Período fechado":data?.balanced?"Débitos e créditos conferidos":"Balancete com diferença"}</span></section>
 <nav className="tabs accounting-tabs"><button className={`tab ${tab==="trial"?"active":""}`} onClick={()=>setTab("trial")}>Balancete</button><button className={`tab ${tab==="ledger"?"active":""}`} onClick={()=>setTab("ledger")}>Razonete</button><button className={`tab ${tab==="chart"?"active":""}`} onClick={()=>setTab("chart")}>Plano de contas</button><button className={`tab ${tab==="tax"?"active":""}`} onClick={()=>setTab("tax")}>Tributos</button></nav>
 {data&&<div className="accounting-kpis"><article><span>Total de débitos</span><strong>{money(data.total_debit)}</strong></article><article><span>Total de créditos</span><strong>{money(data.total_credit)}</strong></article><article><span>Diferença</span><strong className={data.balanced?"positive":"negative"}>{money(data.difference)}</strong></article><article><span>Regras tributárias vigentes</span><strong>{taxes.filter(t=>t.active&&t.effective_from<=end&&(!t.effective_to||t.effective_to>=start)).length}</strong></article></div>}
 {tab==="trial"&&<AccountingTable rows={activeRows} onOpen={openLedger}/>} {tab==="chart"&&<><div className="chart-glossary-intro"><span className="chart-glossary-icon">i</span><div><strong>Como ler o plano de contas</strong><p>É a estrutura que organiza todos os registros contábeis. Passe o mouse ou toque no ícone <b>i</b> ao lado de cada item para entender sua finalidade. Contas em destaque agrupam outras contas; contas analíticas recebem os lançamentos.</p></div></div><AccountingTable rows={data?.rows||[]} onOpen={openLedger} chartOnly/></>}
 {tab==="ledger"&&(ledger?<section><h3>Razonete · {ledger.account.code} {ledger.account.name}</h3><div className="table-scroll"><table className="data-table"><thead><tr><th>Data</th><th>Lançamento</th><th>Origem</th><th>Débito</th><th>Crédito</th><th>Saldo</th><th>Tributo</th></tr></thead><tbody>{ledger.rows.map(r=><tr key={`${r.entry_id}-${r.debit}-${r.credit}`}><td>{r.date}</td><td>{r.memo}</td><td>{r.source_type} #{r.source_id}</td><td>{money(r.debit)}</td><td>{money(r.credit)}</td><td>{money(r.balance)}</td><td>{r.tax_code?`${r.tax_code} · ${r.tax_rate}%`:"—"}</td></tr>)}</tbody></table></div></section>:<div className="empty-state">Clique em uma conta analítica no Balancete para abrir seu razonete.</div>)}
 {tab==="tax"&&<section><div className="section-heading"><div><h3>Regras tributárias versionadas</h3><p>As alíquotas são copiadas para cada lançamento e não alteram o passado. A atualização automática ocorre às 06:00 e 23:59 (Brasília), sempre como proposta para conferência humana.</p></div>{canManage&&<button className="btn-primary" onClick={()=>setTaxOpen(true)}>Nova vigência</button>}</div><div className="table-scroll"><table className="data-table"><thead><tr><th>Tributo</th><th>Alíquota</th><th>Início</th><th>Fim</th><th>Base legal</th><th>Status</th><th>Ações</th></tr></thead><tbody>{taxes.map(t=><tr key={t.id}><td>{t.tax_code} · {t.name}</td><td>{t.rate_percent}%</td><td>{t.effective_from}</td><td>{t.effective_to||"Em aberto"}</td><td>{t.source_url?<a href={t.source_url} target="_blank" rel="noreferrer">{t.legal_basis||"Fonte oficial"}</a>:t.legal_basis||"—"}</td><td><span className={`stock-badge ${t.active?"ok":"warning"}`}>{t.active?"Ativa":"Aguardando aprovação"}</span></td><td>{canManage&&!t.active?<button className="btn-ghost" onClick={()=>activateTax(t)}>Revisar e ativar</button>:"—"}</td></tr>)}{!taxes.length&&<tr><td colSpan={7} className="empty-state">Nenhuma regra configurada. Os lançamentos permanecem sem cálculo tributário até parametrização pelo contador.</td></tr>}</tbody></table></div></section>}
 {taxOpen&&<div className="modal-backdrop" onClick={()=>setTaxOpen(false)}><form className="modal-card" onSubmit={saveTax} onClick={e=>e.stopPropagation()}><h3>Nova vigência tributária</h3><p>Confirme a regra com a contabilidade antes de ativar.</p><div className="accounting-validity-hint"><strong>Vigência contínua</strong><span>Se o fim ficar vazio, a regra permanece válida. Ao cadastrar uma nova vigência do mesmo código, a anterior termina automaticamente no dia anterior.</span></div><div className="form-grid"><Field label="Nome"><input className="input" required value={taxForm.name} onChange={e=>setTaxForm({...taxForm,name:e.target.value})}/></Field><Field label="Código"><input className="input" required placeholder="ISS, PIS, COFINS..." value={taxForm.tax_code} onChange={e=>setTaxForm({...taxForm,tax_code:e.target.value.toUpperCase()})}/></Field><Field label="Alíquota (%)"><input className="input" required type="number" min="0" max="100" step="0.0001" value={taxForm.rate_percent} onChange={e=>setTaxForm({...taxForm,rate_percent:e.target.value})}/></Field><Field label="Início da vigência"><input className="input" required type="date" value={taxForm.effective_from} onChange={e=>setTaxForm({...taxForm,effective_from:e.target.value})}/></Field><Field label="Fim da vigência (opcional)"><input className="input" type="date" min={taxForm.effective_from} value={taxForm.effective_to} onChange={e=>setTaxForm({...taxForm,effective_to:e.target.value})}/><small>Deixe vazio para manter em aberto.</small></Field><Field label="Base legal"><input className="input" value={taxForm.legal_basis} onChange={e=>setTaxForm({...taxForm,legal_basis:e.target.value})}/></Field><Field label="URL da fonte oficial"><input className="input" type="url" value={taxForm.source_url} onChange={e=>setTaxForm({...taxForm,source_url:e.target.value})}/></Field></div><div className="modal-actions"><button className="btn-primary">Salvar e ativar vigência</button><button className="btn-ghost" type="button" onClick={()=>setTaxOpen(false)}>Cancelar</button></div></form></div>}
 {confirmAction&&<div className="modal-backdrop" onClick={()=>!actionBusy&&setConfirmAction(null)}><section className="modal-card accounting-confirm" role="dialog" aria-modal="true" aria-labelledby="accounting-confirm-title" onClick={e=>e.stopPropagation()}><div className={`accounting-confirm-icon ${confirmAction.kind==="close"?"is-warning":"is-info"}`}>{confirmAction.kind==="close"?"✓":"↻"}</div><div><span className="accounting-confirm-eyebrow">{confirmAction.kind==="close"?"Fechamento contábil":"Vigência tributária"}</span><h3 id="accounting-confirm-title">{confirmAction.kind==="close"?"Confirmar fechamento do período?":`Ativar ${confirmAction.tax.tax_code}?`}</h3><p>{confirmAction.kind==="close"?<>O período de <strong>{formatDate(start)}</strong> a <strong>{formatDate(end)}</strong> será bloqueado para novos lançamentos e alterações.</>:<>A regra entra em vigor em <strong>{formatDate(confirmAction.tax.effective_from)}</strong>. A vigência anterior do mesmo tributo será encerrada automaticamente.</>}</p></div>{confirmAction.kind==="close"&&<div className="accounting-confirm-summary"><span>Débitos<strong>{money(data?.total_debit||0)}</strong></span><span>Créditos<strong>{money(data?.total_credit||0)}</strong></span><span>Diferença<strong>{money(data?.difference||0)}</strong></span></div>}<div className="modal-actions"><button className="btn-primary" type="button" disabled={actionBusy} onClick={confirmOperation}>{actionBusy?"Processando...":confirmAction.kind==="close"?"Sim, fechar período":"Ativar vigência"}</button><button className="btn-ghost" type="button" disabled={actionBusy} onClick={()=>setConfirmAction(null)}>Voltar</button></div></section></div>}
 </div>
}
function AccountingTable({rows,onOpen,chartOnly=false}:{rows:Row[];onOpen:(r:Row)=>void;chartOnly?:boolean}){return <div className="table-scroll"><table className="data-table accounting-table"><thead><tr><th>{chartOnly?<GlossaryLabel label="Código" text="Numeração hierárquica que indica onde a conta está no plano. Ex.: 5 é Despesas; 5.1.01 é Combustíveis."/>:"Código"}</th><th>{chartOnly?<GlossaryLabel label="Conta" text="Nome da categoria ou da conta contábil usada para classificar os movimentos."/>:"Conta"}</th>{!chartOnly&&<><th>Saldo anterior</th><th>Débito</th><th>Crédito</th><th>Saldo atual</th></>}<th>{chartOnly?<GlossaryLabel label="Natureza" text="Indica o lado em que o saldo normalmente aumenta. Devedora cresce com débitos; credora cresce com créditos."/>:"Natureza"}</th></tr></thead><tbody>{rows.map(r=>{const description=accountGlossary[r.code]||`${r.accepts_entries?"Conta analítica que recebe lançamentos":"Conta agrupadora que resume as contas abaixo dela"}.`;return <tr key={r.id} className={r.accepts_entries?"account-leaf":"account-group"} onClick={()=>onOpen(r)}><td>{r.code}</td><td><span className="account-name-with-help">{r.name}{chartOnly&&<GlossaryTip text={description}/>}</span></td>{!chartOnly&&<><td>{money(r.opening)}</td><td>{money(r.debit)}</td><td>{money(r.credit)}</td><td className={r.balance<0?"negative":""}>{money(r.balance)}</td></>}<td><span className="account-nature">{r.nature==="debit"?"Devedora":"Credora"}{chartOnly&&<GlossaryTip text={r.nature==="debit"?"Normalmente aumenta quando recebe um débito e diminui quando recebe um crédito.":"Normalmente aumenta quando recebe um crédito e diminui quando recebe um débito."}/>}</span></td></tr>})}</tbody></table></div>}
function GlossaryLabel({label,text}:{label:string;text:string}){return <span className="glossary-label">{label}<GlossaryTip text={text}/></span>}
function GlossaryTip({text}:{text:string}){return <span className="glossary-tip" tabIndex={0} role="button" aria-label={text} onClick={event=>event.stopPropagation()}><span aria-hidden="true">i</span><span className="glossary-tooltip" role="tooltip">{text}</span></span>}
const accountGlossary:Record<string,string>={
 "1":"Ativo reúne bens e direitos controlados pela empresa, como dinheiro e valores a receber.",
 "1.1":"Ativo circulante agrupa recursos que devem virar dinheiro ou ser realizados no curto prazo.",
 "1.1.01":"Caixa e bancos registra o dinheiro disponível em contas bancárias e caixa.",
 "1.1.02":"Contas a receber registra valores que clientes ainda devem pagar à empresa.",
 "2":"Passivo reúne obrigações e dívidas que a empresa precisa pagar.",
 "2.1":"Passivo circulante agrupa obrigações com vencimento no curto prazo.",
 "2.1.01":"Contas a pagar registra valores devidos a fornecedores e outros credores.",
 "2.2.01":"Tributos a recolher registra impostos calculados que ainda serão pagos ao governo.",
 "3":"Patrimônio líquido representa os recursos próprios e o resultado acumulado da empresa.",
 "3.1.01":"Resultados acumulados reúne lucros ou prejuízos transferidos de períodos anteriores.",
 "4":"Receitas agrupa valores gerados pela prestação dos serviços da empresa.",
 "4.1.01":"Receita de fretes registra o faturamento dos serviços de transporte realizados.",
 "5":"Despesas reúne os gastos necessários para manter e executar a operação.",
 "5.1.01":"Combustíveis registra abastecimentos e demais gastos classificados como combustível.",
 "5.1.02":"Manutenção registra gastos com conservação e reparação da frota e de equipamentos.",
 "5.1.03":"Diárias e pessoal registra diárias de motoristas, ajudantes e outros custos de pessoal da operação.",
 "5.1.99":"Outras despesas operacionais recebe gastos da operação que não se encaixam nas categorias específicas.",
 "6":"Tributos e deduções agrupa impostos e valores que reduzem o resultado do faturamento.",
 "6.1.01":"Tributos sobre faturamento registra impostos calculados sobre as receitas, conforme as regras vigentes.",
};
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function periodCadence(start:string,end:string){const days=(new Date(end).getTime()-new Date(start).getTime())/86400000+1;return days<=1?"daily":days<=7?"weekly":"monthly"}
function formatDate(value:string){return new Date(`${value}T12:00:00`).toLocaleDateString("pt-BR")}
