import {useEffect,useState} from "react";
import api from "../services/api";
type Point={month:string;revenue:number;expense:number;payable:number;receivable:number};type Rank={label:string;value:number};
type Data={kpis:{revenue:number;expense:number;result:number;margin_percent:number;pending_payable:number;pending_receivable:number};monthly:Point[];expense_by_category:Rank[];payable_by_category:Rank[];receivable_by_category:Rank[];vehicle_cost:Rank[];route_revenue:Rank[];customer_revenue:Rank[];operations:{inventory_value:number;maintenance_cost:number;low_stock_items:number}};
const empty:Data={kpis:{revenue:0,expense:0,result:0,margin_percent:0,pending_payable:0,pending_receivable:0},monthly:[],expense_by_category:[],payable_by_category:[],receivable_by_category:[],vehicle_cost:[],route_revenue:[],customer_revenue:[],operations:{inventory_value:0,maintenance_cost:0,low_stock_items:0}};
const money=(value:number)=>value.toLocaleString("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0});
export default function FinancialDashboard(){const [data,setData]=useState<Data>(empty),[months,setMonths]=useState(12),[loading,setLoading]=useState(true);useEffect(()=>{setLoading(true);api.get<Data>("/erp/financial-dashboard",{params:{months}}).then(response=>setData(response.data)).finally(()=>setLoading(false))},[months]);const bestCustomer=data.customer_revenue[0],costliest=data.vehicle_cost[0];return <div className="page-card financial-dashboard"><div className="page-header"><div><h2>Dashboard financeiro</h2><p className="page-subtitle">Visão executiva do realizado, planejamento e custos operacionais.</p></div><select className="input dashboard-period" value={months} onChange={event=>setMonths(Number(event.target.value))}><option value={6}>Últimos 6 meses</option><option value={12}>Últimos 12 meses</option><option value={24}>Últimos 24 meses</option></select></div>{loading&&<p className="empty-state">Atualizando indicadores...</p>}
  <div className="finance-kpis"><Kpi label="Receitas" value={money(data.kpis.revenue)} tone="green"/><Kpi label="Despesas" value={money(data.kpis.expense)} tone="red"/><Kpi label="Resultado" value={money(data.kpis.result)} tone={data.kpis.result>=0?"green":"red"}/><Kpi label="Margem" value={`${data.kpis.margin_percent.toFixed(1)}%`}/><Kpi label="A receber" value={money(data.kpis.pending_receivable)} tone="blue"/><Kpi label="A pagar" value={money(data.kpis.pending_payable)} tone="amber"/></div>
  <div className="dashboard-insights"><article><strong>{costliest?.label||"-"}</strong><span>placa com maior custo · {money(costliest?.value||0)}</span></article><article><strong>{bestCustomer?.label||"-"}</strong><span>cliente com maior receita · {money(bestCustomer?.value||0)}</span></article><article><strong>{money(data.operations.inventory_value)}</strong><span>capital estimado no estoque · {data.operations.low_stock_items} itens para repor</span></article><article><strong>{money(data.operations.maintenance_cost)}</strong><span>custo de manutenção no período</span></article></div>
  <section className="chart-card chart-wide"><header><div><h3>Evolução financeira</h3><p>Receitas e despesas realizadas por mês.</p></div><div className="chart-legend"><span className="revenue">Receita</span><span className="expense">Despesa</span></div></header><LineChart rows={data.monthly}/></section>
  <div className="dashboard-chart-grid"><section className="chart-card"><header><div><h3>Planejamento mensal</h3><p>Volume previsto de contas a pagar e receber.</p></div></header><GroupedBars rows={data.monthly}/></section><Chart title="Despesas por centro de custo" subtitle="Composição das despesas realizadas." rows={data.expense_by_category} color="#e45b65"/></div>
  <div className="dashboard-chart-grid"><Chart title="Contas a pagar por categoria" subtitle="Compromissos planejados no período." rows={data.payable_by_category} color="#f59e0b"/><Chart title="Contas a receber por categoria" subtitle="Entradas planejadas no período." rows={data.receivable_by_category} color="#2563eb"/></div>
  <div className="dashboard-chart-grid dashboard-chart-grid-3"><Chart title="Placas com maior custo" subtitle="Despesas e manutenção por veículo." rows={data.vehicle_cost} color="#e45b65"/><Chart title="Receita por cliente" subtitle="Rateio por clientes atendidos nas rotas." rows={data.customer_revenue} color="#13ad8d"/><Chart title="Receita por rota" subtitle="Rotas com maior faturamento." rows={data.route_revenue} color="#2563eb"/></div>
 </div>}
function Kpi({label,value,tone=""}:{label:string;value:string;tone?:string}){return <article className={`finance-kpi ${tone}`}><span>{label}</span><strong>{value}</strong></article>}
function Chart({title,subtitle,rows,color}:{title:string;subtitle:string;rows:Rank[];color:string}){return <section className="chart-card"><header><div><h3>{title}</h3><p>{subtitle}</p></div></header><HorizontalBars rows={rows} color={color}/></section>}
function HorizontalBars({rows,color}:{rows:Rank[];color:string}){const max=Math.max(...rows.map(row=>row.value),1);if(!rows.length)return <div className="chart-empty">Sem dados no período.</div>;return <div className="horizontal-bars">{rows.map(row=><div className="horizontal-bar" key={row.label}><div><span title={row.label}>{row.label}</span><strong>{money(row.value)}</strong></div><i><b style={{width:`${row.value/max*100}%`,background:color}}/></i></div>)}</div>}
function LineChart({rows}:{rows:Point[]}){if(!rows.length)return <div className="chart-empty">Sem dados no período.</div>;const max=Math.max(...rows.flatMap(row=>[row.revenue,row.expense]),1),w=900,h=240,p=24,x=(index:number)=>p+index*(w-p*2)/Math.max(rows.length-1,1),y=(value:number)=>h-p-value/max*(h-p*2),points=(key:"revenue"|"expense")=>rows.map((row,index)=>`${x(index)},${y(row[key])}`).join(" ");return <div className="line-chart"><svg viewBox={`0 0 ${w} ${h}`} role="img" aria-label="Evolução mensal de receitas e despesas"><line x1={p} y1={h-p} x2={w-p} y2={h-p} className="chart-axis"/><polyline points={points("revenue")} className="chart-line revenue"/><polyline points={points("expense")} className="chart-line expense"/>{rows.map((row,index)=><g key={row.month}><circle cx={x(index)} cy={y(row.revenue)} r="4" className="chart-dot revenue"><title>{row.month}: receita {money(row.revenue)}</title></circle><circle cx={x(index)} cy={y(row.expense)} r="4" className="chart-dot expense"><title>{row.month}: despesa {money(row.expense)}</title></circle></g>)}</svg><div className="chart-months">{rows.map(row=><span key={row.month}>{row.month.slice(5)}/{row.month.slice(2,4)}</span>)}</div></div>}
function GroupedBars({rows}:{rows:Point[]}){const max=Math.max(...rows.flatMap(row=>[row.payable,row.receivable]),1);return <div className="grouped-bars">{rows.map(row=><div className="grouped-month" key={row.month}><div><i className="payable" style={{height:`${Math.max(row.payable/max*150,2)}px`}} title={`A pagar: ${money(row.payable)}`}/><i className="receivable" style={{height:`${Math.max(row.receivable/max*150,2)}px`}} title={`A receber: ${money(row.receivable)}`}/></div><span>{row.month.slice(5)}</span></div>)}</div>}
