import { FormEvent, ReactNode, useEffect, useMemo, useState } from "react";
import api from "../services/api";
import { useAuth } from "../context/AuthContext";

type Supplier={id:number;legal_name:string;trade_name?:string;document:string};
type Item={description:string;quantity:string;unit:string;unit_price:string};
type Ticket={id:number;ticket:string;department:string;description:string;amount:number;supplier_name:string;document?:string;status:string;requester_name:string;approver_name?:string;rejection_reason?:string;financial_account_id?:number;purchased_at?:string;delivery_due_date?:string;sla_status:string;created_at:string};
type ActionKind="review"|"submit"|"approve"|"adjust"|"reject"|"purchase"|"receive";
const blank=()=>({department:"frota",description:"",supplier_id:"",category:"outros",document:"",due_date:new Date().toISOString().slice(0,10),cost_center:"",items:[{description:"",quantity:"1",unit:"un",unit_price:""}] as Item[]});
const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const labels:Record<string,string>={solicitada:"Aguardando Compras",em_analise:"Em análise por Compras",aguardando_aprovacao:"Aguardando aprovação",ajuste_solicitado:"Devolvida para ajuste",aprovada:"Aprovada — comprar",rejeitada:"Recusada",comprada:"Aguardando entrega",recebida:"Recebida"};
const sla:Record<string,string>={pending:"Aguardando execução",on_time:"No prazo",attention:"Atenção",overdue:"Vencido",completed_on_time:"Recebido no prazo",completed_late:"Recebido com atraso"};
const actionTitles:Record<ActionKind,string>={review:"Iniciar análise",submit:"Enviar para aprovação",approve:"Aprovar solicitação",adjust:"Solicitar ajuste",reject:"Recusar solicitação",purchase:"Registrar compra",receive:"Confirmar recebimento"};

export default function Purchases(){
 const{user,hasRole}=useAuth(),canApprove=hasRole("admin_global","gestor_brasil","gestor_financeiro"),canPurchase=hasRole("admin_global","gestor_brasil","gestor_financeiro","operador_logistico");
 const[rows,setRows]=useState<Ticket[]>([]),[suppliers,setSuppliers]=useState<Supplier[]>([]),[open,setOpen]=useState(false),[form,setForm]=useState(blank()),[filter,setFilter]=useState(""),[error,setError]=useState("");
 const[action,setAction]=useState<{kind:ActionKind;ticket:Ticket}|null>(null),[note,setNote]=useState(""),[deliveryDate,setDeliveryDate]=useState(""),[busy,setBusy]=useState(false);
 const load=()=>Promise.all([api.get<Ticket[]>("/erp/purchases"),api.get<Supplier[]>("/suppliers?only_active=true")]).then(([r,s])=>{setRows(r.data);setSuppliers(s.data)});useEffect(()=>{load()},[]);
 const total=(a:Item[])=>a.reduce((s,x)=>s+(Number(x.quantity)||0)*(Number(x.unit_price)||0),0),filtered=useMemo(()=>rows.filter(x=>!filter||x.status===filter),[rows,filter]);
 function setItem(i:number,k:keyof Item,v:string){const items=[...form.items];items[i]={...items[i],[k]:v};setForm({...form,items})}
 function showAction(kind:ActionKind,ticket:Ticket){setError("");setNote("");setDeliveryDate("");setAction({kind,ticket})}
 async function save(e:FormEvent){e.preventDefault();setError("");try{await api.post("/erp/purchases",{...form,branch_id:user?.branch_id,amount:total(form.items),supplier_id:Number(form.supplier_id),items:form.items.map(x=>({...x,quantity:Number(x.quantity),unit_price:Number(x.unit_price)}))});setOpen(false);setForm(blank());await load()}catch(err:any){setError(err?.response?.data?.detail||"Não foi possível enviar a solicitação.")}}
 async function runAction(e:FormEvent){e.preventDefault();if(!action)return;setBusy(true);setError("");try{const id=action.ticket.id;if(action.kind==="review")await api.post(`/erp/purchases/${id}/start-review`,{note});if(action.kind==="submit")await api.post(`/erp/purchases/${id}/submit-approval`,{note});if(action.kind==="approve")await api.post(`/erp/purchases/${id}/approve`);if(action.kind==="adjust")await api.post(`/erp/purchases/${id}/request-adjustment`,{note});if(action.kind==="reject")await api.post(`/erp/purchases/${id}/reject`,{reason:note});if(action.kind==="purchase")await api.post(`/erp/purchases/${id}/purchased`,{delivery_due_date:deliveryDate});if(action.kind==="receive")await api.post(`/erp/purchases/${id}/received`);setAction(null);await load()}catch(err:any){setError(err?.response?.data?.detail||"Não foi possível concluir a ação.")}finally{setBusy(false)}}
 const needsNote=action&&["review","submit","adjust","reject"].includes(action.kind);
 return <div><div className="page-header"><div><h2>Compras e tarefas</h2><p className="page-subtitle">Solicitação, análise de Compras, aprovação financeira, entrega e recebimento.</p></div><button className="btn-primary btn-add" onClick={()=>{setError("");setOpen(true)}}>+ Nova solicitação</button></div>
 <div className="purchase-kpis"><article><span>Na fila de Compras</span><strong>{rows.filter(x=>["solicitada","em_analise","ajuste_solicitado"].includes(x.status)).length}</strong></article><article><span>Aguardando aprovação</span><strong>{rows.filter(x=>x.status==="aguardando_aprovacao").length}</strong></article><article><span>Compras e entregas</span><strong>{rows.filter(x=>["aprovada","comprada"].includes(x.status)).length}</strong></article><article><span>SLA vencido</span><strong>{rows.filter(x=>x.sla_status==="overdue").length}</strong></article></div>
 <section className="card-panel purchase-filter"><select className="input" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todos os status</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></section>
 <div className="table-scroll"><table className="data-table"><thead><tr><th>Ticket</th><th>Fornecedor</th><th>Solicitação</th><th>Valor</th><th>Etapa atual</th><th>Entrega</th><th>SLA</th><th>Ações</th></tr></thead><tbody>{filtered.length===0&&<tr><td colSpan={8}>Nenhuma solicitação encontrada.</td></tr>}{filtered.map(x=><tr key={x.id}><td><strong>{x.ticket}</strong><small>{new Date(x.created_at).toLocaleDateString("pt-BR")}</small></td><td>{x.supplier_name}<small>{x.document||"Sem documento"}</small></td><td>{x.description}<small>{x.requester_name} · {x.department}</small>{x.rejection_reason&&<small className="purchase-return">Retorno: {x.rejection_reason}</small>}</td><td>{money(Number(x.amount))}</td><td><span className={`purchase-stage stage-${x.status}`}>{labels[x.status]||x.status}</span>{x.approver_name&&<small>Aprovado por {x.approver_name}</small>}</td><td>{x.delivery_due_date?new Date(`${x.delivery_due_date}T12:00`).toLocaleDateString("pt-BR"):"—"}{x.purchased_at&&<small>Compra: {new Date(x.purchased_at).toLocaleDateString("pt-BR")}</small>}</td><td><span className={`driver-status ${x.sla_status==="overdue"?"expired":x.sla_status==="attention"||x.sla_status==="pending"?"warning":"ok"}`}>{sla[x.sla_status]||x.sla_status}</span>{x.financial_account_id&&<small>Conta a pagar #{x.financial_account_id}</small>}</td><td><Actions row={x} canPurchase={canPurchase} canApprove={canApprove} run={showAction}/></td></tr>)}</tbody></table></div>
 {open&&<div className="modal-backdrop" onClick={()=>setOpen(false)}><form className="modal-card driver-modal" onSubmit={save} onClick={e=>e.stopPropagation()}><ModalHead title="Nova solicitação de compra" subtitle="O pedido será encaminhado ao setor de Compras para análise." close={()=>setOpen(false)}/><div className="form-grid"><Field label="Fornecedor"><select className="input" required value={form.supplier_id} onChange={e=>setForm({...form,supplier_id:e.target.value})}><option value="">Selecione</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.trade_name||s.legal_name} · {s.document}</option>)}</select></Field>{([['department','Setor solicitante'],['cost_center','Centro de custo'],['category','Categoria'],['document','Documento/referência']] as const).map(([k,l])=><Field label={l} key={k}><input className="input" required={k!=="document"} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></Field>)}<Field label="Vencimento pretendido"><input className="input" type="date" required value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/></Field></div><Field label="Justificativa e necessidade"><textarea className="input" required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><h4>Itens solicitados</h4>{form.items.map((x,i)=><div className="purchase-item" key={i}><input className="input" required placeholder="Produto ou serviço" value={x.description} onChange={e=>setItem(i,"description",e.target.value)}/><input className="input" type="number" min=".001" step=".001" value={x.quantity} onChange={e=>setItem(i,"quantity",e.target.value)}/><input className="input" value={x.unit} onChange={e=>setItem(i,"unit",e.target.value)}/><input className="input" type="number" min="0" step=".01" value={x.unit_price} onChange={e=>setItem(i,"unit_price",e.target.value)}/><button type="button" className="btn-mini danger" disabled={form.items.length===1} onClick={()=>setForm({...form,items:form.items.filter((_,n)=>n!==i)})}>×</button></div>)}<button type="button" className="btn-ghost" onClick={()=>setForm({...form,items:[...form.items,{description:"",quantity:"1",unit:"un",unit_price:""}]})}>+ Adicionar item</button><div className="purchase-total"><span>Total estimado</span><strong>{money(total(form.items))}</strong></div>{error&&<p className="modal-error">{error}</p>}<div className="modal-actions"><button className="btn-primary">Enviar solicitação</button><button type="button" className="btn-ghost" onClick={()=>setOpen(false)}>Cancelar</button></div></form></div>}
 {action&&<div className="modal-backdrop" onClick={()=>!busy&&setAction(null)}><form className="modal-card purchase-action-modal" onSubmit={runAction} onClick={e=>e.stopPropagation()}><ModalHead title={actionTitles[action.kind]} subtitle={`${action.ticket.ticket} · ${action.ticket.description}`} close={()=>setAction(null)}/>{needsNote&&<Field label={action.kind==="reject"?"Motivo da recusa":action.kind==="adjust"?"Ajustes necessários":"Parecer da etapa"}><textarea className="input" autoFocus required minLength={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Registre a decisão e as orientações para o solicitante."/></Field>}{action.kind==="purchase"&&<><Field label="Data da compra"><input className="input" type="date" value={new Date().toISOString().slice(0,10)} disabled/></Field><Field label="Previsão de entrega"><input className="input" type="date" autoFocus required min={new Date().toISOString().slice(0,10)} value={deliveryDate} onChange={e=>setDeliveryDate(e.target.value)}/></Field></>}{action.kind==="approve"&&<p>A aprovação criará automaticamente a conta a pagar vinculada.</p>}{action.kind==="receive"&&<p>Confirme após conferir os itens. Data e responsável serão registrados.</p>}{error&&<p className="modal-error">{error}</p>}<div className="modal-actions"><button className="btn-primary" disabled={busy}>{busy?"Processando...":actionTitles[action.kind]}</button><button type="button" className="btn-ghost" disabled={busy} onClick={()=>setAction(null)}>Cancelar</button></div></form></div>}</div>
}

function Actions({row,canPurchase,canApprove,run}:{row:Ticket;canPurchase:boolean;canApprove:boolean;run:(kind:ActionKind,row:Ticket)=>void}){return <div className="occurrence-actions">{canPurchase&&row.status==="solicitada"&&<button className="btn-primary btn-mini" onClick={()=>run("review",row)}>Analisar</button>}{canPurchase&&row.status==="em_analise"&&<><button className="btn-primary btn-mini" onClick={()=>run("submit",row)}>Enviar para aprovação</button><button className="btn-ghost btn-mini" onClick={()=>run("adjust",row)}>Pedir ajuste</button></>}{canApprove&&row.status==="aguardando_aprovacao"&&<><button className="btn-primary btn-mini" onClick={()=>run("approve",row)}>Aprovar</button><button className="btn-ghost btn-mini" onClick={()=>run("adjust",row)}>Pedir ajuste</button><button className="btn-mini danger" onClick={()=>run("reject",row)}>Recusar</button></>}{canPurchase&&row.status==="ajuste_solicitado"&&<button className="btn-primary btn-mini" onClick={()=>run("review",row)}>Reanalisar</button>}{canPurchase&&row.status==="aprovada"&&<button className="btn-primary btn-mini" onClick={()=>run("purchase",row)}>Registrar compra</button>}{canPurchase&&row.status==="comprada"&&<button className="btn-primary btn-mini" onClick={()=>run("receive",row)}>Confirmar recebimento</button>}</div>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function ModalHead({title,subtitle,close}:{title:string;subtitle:string;close:()=>void}){return <div className="modal-heading"><div><h3>{title}</h3><p>{subtitle}</p></div><button type="button" className="modal-close" onClick={close}>×</button></div>}
