import { useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import api from "../services/api";
import { useAuth } from "../context/AuthContext";
import {appConfirm} from "../components/AppDialog";

interface RevenueItem { id:number; route_id?:number|null; route_ids?:number[]; route_codes?:string[]; route_codigo_ut?:string|null; billed_customer_name?:string|null; revenue_date:string; amount:number|string; notes?:string|null; source:string; created_at:string; created_by_name?:string|null; customers?:string[]; financial_account_id?:number|null; financial_status?:string|null; }
interface RouteItem { id:number; codigo_ut:string; route_date:string; status:string; stops?:Array<{client_name?:string|null;customer_name?:string|null}>; }
const today=()=>new Date().toISOString().slice(0,10);const currentMonth=()=>today().slice(0,7);

export default function Revenues(){
  const {t,i18n}=useTranslation(),{hasPermission}=useAuth();
  const canManage=hasPermission("finance.revenue.manage","gestor_financeiro");
  const [revenues,setRevenues]=useState<RevenueItem[]>([]),[routes,setRoutes]=useState<RouteItem[]>([]),[month,setMonth]=useState(currentMonth()),[query,setQuery]=useState(""),[source,setSource]=useState(""),[editing,setEditing]=useState<RevenueItem|"new"|null>(null),[error,setError]=useState("");
  const [form,setForm]=useState({revenue_date:today(),amount:"",notes:"",billed_customer_name:"",route_ids:[] as number[]});
  const reload=()=>api.get<RevenueItem[]>("/revenues",{params:{month}}).then(r=>setRevenues(r.data)).catch(()=>setRevenues([]));
  useEffect(()=>{reload()},[month]);
  useEffect(()=>{if(canManage)api.get<RouteItem[]>("/routes").then(r=>setRoutes(r.data)).catch(()=>setRoutes([]))},[canManage]);
  const filtered=useMemo(()=>revenues.filter(row=>{const text=`${row.route_codigo_ut||row.route_id||""} ${(row.customers||[]).join(" ")} ${row.notes||""}`.toLowerCase();return(!query||text.includes(query.toLowerCase()))&&(!source||row.source===source)}),[revenues,query,source]);
  const total=useMemo(()=>filtered.reduce((sum,row)=>sum+Number(row.amount||0),0),[filtered]);
  const routeCustomers=(route:RouteItem)=>[...new Set((route.stops||[]).map(stop=>(stop.client_name||stop.customer_name||"").trim()).filter(Boolean))];
  const customers=useMemo(()=>[...new Set(routes.flatMap(routeCustomers))].sort((a,b)=>a.localeCompare(b,"pt-BR")),[routes]);
  const billedRouteIds=useMemo(()=>new Set(revenues.filter(revenue=>revenue.source==="manual").flatMap(revenue=>revenue.route_ids?.length?revenue.route_ids:revenue.route_id?[revenue.route_id]:[])),[revenues]);
  const availableRoutes=useMemo(()=>routes.filter(route=>routeCustomers(route).includes(form.billed_customer_name)&&(!billedRouteIds.has(route.id)||form.route_ids.includes(route.id))),[routes,form.billed_customer_name,form.route_ids,billedRouteIds]);
  function startNew(){setError("");setForm({revenue_date:today(),amount:"",notes:"",billed_customer_name:"",route_ids:[]});setEditing("new")}
  function startEdit(row:RevenueItem){setError("");setForm({revenue_date:row.revenue_date,amount:String(row.amount||""),notes:row.notes||"",billed_customer_name:row.billed_customer_name||row.customers?.[0]||"",route_ids:row.route_ids?.length?row.route_ids:row.route_id?[row.route_id]:[]});setEditing(row)}
  function toggleRoute(routeId:number){setForm(current=>({...current,route_ids:current.route_ids.includes(routeId)?current.route_ids.filter(id=>id!==routeId):[...current.route_ids,routeId]}))}
  async function save(event:React.FormEvent){event.preventDefault();setError("");if(!form.billed_customer_name||!form.route_ids.length||!form.amount){setError("Informe o cliente, selecione ao menos uma rota e preencha o valor.");return}const createPayload={revenue_date:form.revenue_date,amount:Number(form.amount),notes:form.notes.trim()||null,billed_customer_name:form.billed_customer_name,route_ids:form.route_ids};const updatePayload={revenue_date:form.revenue_date,amount:Number(form.amount),notes:form.notes.trim()||null};try{editing==="new"?await api.post("/revenues",createPayload):await api.put(`/revenues/${(editing as RevenueItem).id}`,updatePayload);setEditing(null);reload()}catch(e:any){setError(e?.response?.data?.detail||t("rev.err_save"))}}
  async function remove(row:RevenueItem){if(!await appConfirm(`Excluir a receita #${row.id} e a conta a receber vinculada? Esta ação não poderá ser desfeita.`,{title:"Excluir receita",confirmLabel:"Sim, excluir",danger:true}))return;try{await api.delete(`/revenues/${row.id}`);reload()}catch(e:any){setError(e?.response?.data?.detail||t("rev.err_delete"))}}
  const routeLabel=(route:RouteItem)=>{const clients=[...new Set((route.stops||[]).map(stop=>stop.client_name||stop.customer_name).filter(Boolean))];return `${route.codigo_ut} · ${route.route_date}${clients.length?` · ${clients.join(", ")}`:""}`};
  return <div>
    <div className="page-header"><div><h2>Receitas</h2><p className="page-subtitle">Faturamento por rota lançado exclusivamente pelo setor financeiro.</p></div><div style={{display:"flex",alignItems:"center",gap:16}}><div style={{textAlign:"right"}}><div style={{fontSize:11,color:"#64748b",textTransform:"uppercase"}}>Total filtrado</div><strong style={{fontSize:22,color:"#059669"}}>{money(total,i18n.language)}</strong></div>{canManage&&<button className="btn-primary btn-add" onClick={startNew}><span className="btn-add-symbol">+</span><span>Nova receita</span></button>}</div></div>
    {error&&<p className="modal-error">{error}</p>}
    <section className="expense-toolbar card-panel revenue-filters"><label className="field"><span>Mês</span><input className="input" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><label className="field"><span>Buscar rota, cliente ou observação</span><input className="input" value={query} placeholder="Digite para filtrar" onChange={e=>setQuery(e.target.value)}/></label><label className="field"><span>Origem</span><select className="input" value={source} onChange={e=>setSource(e.target.value)}><option value="">Todas</option><option value="manual">Manual</option><option value="import">Importação</option></select></label></section>
    {editing&&<div className="modal-backdrop" onClick={()=>setEditing(null)}><form className="modal-card expense-modal" onSubmit={save} onClick={event=>event.stopPropagation()}><h3>{editing==="new"?"Nova receita":"Editar receita"}</h3><p>Uma única receita e conta a receber podem consolidar várias rotas do mesmo cliente.</p><div className="form-grid"><label className="field"><span>Data da receita</span><input className="input" type="date" required value={form.revenue_date} onChange={e=>setForm({...form,revenue_date:e.target.value})}/></label><label className="field"><span>Valor faturado</span><input className="input" type="number" min="0.01" step="0.01" required value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label className="field" style={{gridColumn:"1/-1"}}><span>Cliente faturado</span><select className="input" required disabled={editing!=="new"} value={form.billed_customer_name} onChange={e=>setForm({...form,billed_customer_name:e.target.value,route_ids:[]})}><option value="">Selecione o cliente</option>{customers.map(customer=><option key={customer} value={customer}>{customer}</option>)}</select></label><div className="field" style={{gridColumn:"1/-1"}}><span>Rotas deste cliente</span><div style={{maxHeight:220,overflow:"auto",border:"1px solid var(--border)",borderRadius:8,padding:10,display:"grid",gap:8}}>{!form.billed_customer_name?<small>Selecione o cliente para visualizar as rotas.</small>:availableRoutes.length===0?<small>Nenhuma rota disponível para este cliente.</small>:availableRoutes.map(route=><label key={route.id} style={{display:"flex",gap:10,alignItems:"flex-start",cursor:editing==="new"?"pointer":"default"}}><input type="checkbox" disabled={editing!=="new"} checked={form.route_ids.includes(route.id)} onChange={()=>toggleRoute(route.id)}/><span>{routeLabel(route)}</span></label>)}</div><small>{form.route_ids.length} rota(s) selecionada(s)</small></div></div><label className="field" style={{marginTop:10}}><span>Observações financeiras</span><textarea className="input" style={{minHeight:80}} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>{error&&<p className="modal-error">{error}</p>}<div className="modal-actions"><button className="btn-primary" type="submit">Salvar receita</button><button className="btn-ghost" type="button" onClick={()=>setEditing(null)}>Cancelar</button></div></form></div>}
    <div className="table-scroll"><table className="data-table"><thead><tr><th>Data</th><th>Valor</th><th>Rotas</th><th>Cliente faturado</th><th>Conta a receber</th><th>Lançado por</th><th>Observações</th><th>Ações</th></tr></thead><tbody>{filtered.map(row=><tr key={row.id}><td>{row.revenue_date}</td><td>{money(Number(row.amount),i18n.language)}</td><td>{row.route_codes?.join(", ")||row.route_codigo_ut||row.route_id||"—"}</td><td>{row.billed_customer_name||row.customers?.join(", ")||"—"}</td><td>{row.financial_account_id?<span className={`stock-badge ${row.financial_status==="recebida"?"ok":"warning"}`}>{row.financial_status||"pendente"} · #{row.financial_account_id}</span>:<span className="stock-badge">Legado</span>}</td><td>{row.created_by_name||row.source}</td><td>{row.notes||"—"}</td><td>{canManage?<><button className="btn-mini" onClick={()=>startEdit(row)}>Editar</button><button className="btn-mini danger" onClick={()=>remove(row)}>Excluir</button></>:<span className="expense-source">Somente leitura</span>}</td></tr>)}{!filtered.length&&<tr><td colSpan={8} className="empty-state">Nenhuma receita encontrada no período.</td></tr>}</tbody></table></div>
  </div>
}
function money(value:number,locale="pt-BR"){return new Intl.NumberFormat(locale,{style:"currency",currency:locale==="pt-BR"?"BRL":"EUR"}).format(value)}
