import {useEffect,useMemo,useRef,useState} from "react";
import api from "../services/api";
import {appAlert} from "../components/AppDialog";
import {useAuth} from "../context/AuthContext";
import RouteMap from "../components/RouteMap";
type Live={route_id:number;codigo_ut:string;vehicle_plate?:string;driver_name?:string;latitude:number;longitude:number;speed_kmh?:number;recorded_at:string};
declare global {interface Window{AndroidLocation?:{requestPermission?:()=>void;startLocationUpdates?:(intervalMs:number)=>void;stopLocationUpdates?:()=>void};onAndroidLocation?:(lat:number,lng:number,accuracy?:number,speedMps?:number,recordedAt?:string)=>void}}
export default function Tracking(){
 const {hasRole}=useAuth(),tower=hasRole('admin_global','gestor_brasil','torre_controle');const [live,setLive]=useState<Live[]>([]),[route,setRoute]=useState(''),[watch,setWatch]=useState<number>(),[sharing,setSharing]=useState(false),[selected,setSelected]=useState<number|null>(null),[fullscreen,setFullscreen]=useState(false);const mapShell=useRef<HTMLDivElement|null>(null);
 async function refresh(){if(tower)setLive((await api.get('/tracking/live')).data)}useEffect(()=>{refresh();const timer=setInterval(refresh,30000);return()=>clearInterval(timer)},[]);
 async function send(latitude:number,longitude:number,accuracy?:number,speedMps?:number,recordedAt?:string){await api.post('/tracking/positions',{route_id:Number(route),latitude,longitude,accuracy_m:accuracy,speed_kmh:speedMps==null?null:speedMps*3.6,recorded_at:recordedAt||undefined})}
 async function start(){if(!route)return;await api.put('/tracking/consent',{accepted:true,terms_version:'1.0'});setSharing(true);window.onAndroidLocation=(lat,lng,accuracy,speed,at)=>void send(lat,lng,accuracy,speed,at);if(window.AndroidLocation){window.AndroidLocation.requestPermission?.();window.AndroidLocation.startLocationUpdates?.(120000);return}setWatch(navigator.geolocation.watchPosition(p=>void send(p.coords.latitude,p.coords.longitude,p.coords.accuracy,p.coords.speed??undefined),()=>{setSharing(false);void appAlert('Não foi possível acessar o GPS.',{title:'Localização indisponível'})},{enableHighAccuracy:true,maximumAge:15000}))}
 function stop(){if(watch!==undefined)navigator.geolocation.clearWatch(watch);window.AndroidLocation?.stopLocationUpdates?.();delete window.onAndroidLocation;api.put('/tracking/consent',{accepted:false,terms_version:'1.0'});setWatch(undefined);setSharing(false)}
 useEffect(()=>{const change=()=>setFullscreen(document.fullscreenElement===mapShell.current);document.addEventListener('fullscreenchange',change);return()=>document.removeEventListener('fullscreenchange',change)},[]);
 async function toggleFullscreen(){if(!document.fullscreenElement)await mapShell.current?.requestFullscreen();else await document.exitFullscreen()}
 const mapRoutes=useMemo(()=>live.map(p=>({id:p.route_id,codigo_ut:p.codigo_ut,status:'em_rota',stops:[{id:p.route_id,customer_name:`${p.driver_name||'Motorista'} · ${p.vehicle_plate||'Sem placa'}`,latitude:p.latitude,longitude:p.longitude,status:'em_rota'}]})),[live]);
 return <div className="page-card tracking-page"><div className="page-header"><div><h2>Monitoramento GPS</h2><p className="page-subtitle">Acompanhamento da frota em tempo real dentro do ambiente operacional.</p></div>{tower&&<button className="btn-ghost tracking-fullscreen-btn" onClick={toggleFullscreen}>⛶ Tela cheia</button>}</div>{!tower&&<div className="filter-bar card-panel"><input className="input" type="number" placeholder="ID da rota" value={route} onChange={e=>setRoute(e.target.value)}/>{!sharing?<button className="btn-primary" onClick={start}>Aceitar termo e compartilhar</button>:<button className="btn-danger" onClick={stop}>Parar compartilhamento</button>}<small>{window.AndroidLocation?'Modo Android WebView detectado':'Modo navegador ativo'}</small></div>}{tower&&<><div ref={mapShell} className={`tracking-map-shell${fullscreen?' is-fullscreen':''}`}><RouteMap routes={mapRoutes} selectedRouteId={selected} onSelectRoute={setSelected}/><div className="tracking-map-toolbar"><span>{live.length} veículo{live.length===1?'':'s'} monitorado{live.length===1?'':'s'}</span><button className="btn-primary btn-mini" onClick={toggleFullscreen}>{fullscreen?'✕ Sair da tela cheia':'⛶ Tela cheia'}</button></div></div><div className="card-grid">{live.map(p=><article className="summary-card" key={p.route_id}><h3>{p.codigo_ut} · {p.vehicle_plate||'-'}</h3><p>{p.driver_name||'-'} · {p.speed_kmh?.toFixed(1)||0} km/h</p><small>{new Date(p.recorded_at).toLocaleString('pt-BR')}</small></article>)}</div></>}</div>
}
