import {useEffect,useState} from "react";
import api from "../services/api";
import {useAuth} from "../context/AuthContext";
import {appPrompt} from "../components/AppDialog";

type Task={id:number;source_type:string;source_id:number;title:string;description?:string;requester_id:number;requester_name?:string;current_department:string;assignee_name?:string;status:string;source_status?:string;resolution?:string;priority?:number;created_at:string};
type Event={id:number;action:string;actor_name?:string;from_department?:string;to_department?:string;from_status?:string;to_status?:string;note?:string;created_at:string};
const departments=["Operação","Torre de controle","Frota","Financeiro","Compras","Cadastros","Diretoria"];
const statusLabel:Record<string,string>={open:"Aberta",in_progress:"Em tratamento",returned:"Devolvida ao solicitante",closed:"Finalizada",cancelled:"Cancelada"};
const sourceLabel:Record<string,string>={occurrence:"Ocorrência",expense:"Despesa",purchase:"Compra",maintenance_order:"Ordem de serviço",vehicle_change:"Alteração de veículo",driver_statement:"Contestação de extrato"};
const sourceStatusLabel:Record<string,string>={pending:"Pendente",in_review:"Em análise",adjustment_requested:"Ajuste solicitado",approved:"Aprovada",rejected:"Recusada",open:"Aberta",in_progress:"Em tratamento",returned:"Devolvida",closed:"Finalizada",cancelled:"Cancelada",solicitada:"Solicitada",em_analise:"Em análise",aguardando_aprovacao:"Aguardando aprovação",ajuste_solicitado:"Ajuste solicitado",aprovada:"Aprovada",rejeitada:"Recusada",comprada:"Comprada",recebida:"Recebida"};
const eventLabel:Record<string,string>={created:"Tarefa criada",started:"Tratamento iniciado",transferred:"Transferida de setor",returned:"Devolvida ao solicitante",closed:"Finalizada",source_status_changed:"Situação de origem atualizada",routed_by_source:"Encaminhada pelo fluxo",returned_by_source:"Devolvida pelo fluxo",closed_by_source:"Finalizada pelo fluxo"};

export default function WorkflowTasks(){
 const{user}=useAuth(),[rows,setRows]=useState<Task[]>([]),[selected,setSelected]=useState<Task|null>(null),[history,setHistory]=useState<Event[]>([]),[filter,setFilter]=useState("active"),[error,setError]=useState("");
 const load=()=>api.get<Task[]>("/workflow/tasks").then(r=>setRows(r.data)).catch(e=>setError(e?.response?.data?.detail||"Não foi possível carregar as tarefas."));useEffect(()=>{load()},[]);
 const visible=rows.filter(x=>filter==="all"||(filter==="mine"?x.requester_id===user?.id:!["closed","cancelled"].includes(x.status)));
 async function open(task:Task){setSelected(task);setError("");const r=await api.get<Event[]>(`/workflow/tasks/${task.id}/history`);setHistory(r.data)}
 async function start(task:Task){await api.post(`/workflow/tasks/${task.id}/start`,{note:"Tratamento iniciado."});await load();await open(task)}
 async function transfer(task:Task){const department=await appPrompt(`Setores disponíveis: ${departments.join(" · ")}`,{title:"Transferir tarefa",label:"Setor de destino",initial:task.current_department,required:true,confirmLabel:"Continuar"});if(!department)return;const note=await appPrompt("Explique por que a tarefa está sendo transferida e o que o próximo setor deve fazer.",{title:"Orientação da transferência",label:"Motivo e orientação",required:true,confirmLabel:"Transferir tarefa"});if(!note)return;try{await api.post(`/workflow/tasks/${task.id}/transfer`,{department,note});setSelected(null);load()}catch(e:any){setError(e?.response?.data?.detail||"Não foi possível transferir.")}}
 async function returnTask(task:Task){if(task.source_type==="driver_statement"){await resolveStatement(task);return}const resolution=await appPrompt("Descreva a tratativa ou explicação que será entregue ao solicitante.",{title:"Devolver tratativa",label:"Tratativa realizada",required:true,confirmLabel:"Devolver ao solicitante"});if(!resolution)return;try{await api.post(`/workflow/tasks/${task.id}/return`,{resolution});setSelected(null);load()}catch(e:any){setError(e?.response?.data?.detail||"Não foi possível devolver a tarefa.")}}
 async function resolveStatement(task:Task){const type=await appPrompt("Digite complemento quando faltou valor, ou desconto quando o valor estava maior.",{title:"Ajustar extrato contestado",label:"Tipo: complemento ou desconto",required:true,confirmLabel:"Continuar"});if(!type)return;const normalized=type.toLowerCase().startsWith("compl")?"complement":type.toLowerCase().startsWith("desc")?"deduction":"";if(!normalized){setError("Informe complemento ou desconto.");return}const amount=await appPrompt("Informe o valor exato do ajuste.",{title:"Valor do ajuste",label:"Valor em reais",required:true,confirmLabel:"Continuar"});if(!amount)return;const reason=await appPrompt("Descreva a análise e a correção realizada.",{title:"Conclusão financeira",label:"Motivo do ajuste",required:true,confirmLabel:"Aplicar e liberar extrato"});if(!reason)return;try{await api.post(`/erp/driver-statement-periods/${task.source_id}/resolve`,{adjustment_type:normalized,amount:Number(amount.replace(",",".")),reason});setSelected(null);load()}catch(e:any){setError(e?.response?.data?.detail||"Não foi possível ajustar o extrato.")}}
 async function close(task:Task){const note=await appPrompt("Você pode registrar uma observação final antes de aceitar e encerrar a tarefa.",{title:"Aceitar e finalizar",label:"Observação final (opcional)",confirmLabel:"Finalizar tarefa"});if(note===null)return;try{await api.post(`/workflow/tasks/${task.id}/close`,{note:note||null});setSelected(null);load()}catch(e:any){setError(e?.response?.data?.detail||"Não foi possível finalizar o ticket.")}}
 return <div className="page-card"><div className="page-header"><div><h2>Central de tarefas</h2><p className="page-subtitle">Transferências entre setores, devolução ao solicitante e trilha completa de ações.</p></div></div>{error&&<p className="modal-error">{error}</p>}
 <div className="workflow-kpis"><article><span>Em aberto</span><strong>{rows.filter(x=>x.status==="open").length}</strong></article><article><span>Em tratamento</span><strong>{rows.filter(x=>x.status==="in_progress").length}</strong></article><article><span>Aguardando solicitante</span><strong>{rows.filter(x=>x.status==="returned").length}</strong></article><article><span>Finalizadas</span><strong>{rows.filter(x=>x.status==="closed").length}</strong></article></div>
 <div className="workflow-filter"><button className={filter==="active"?"active":""} onClick={()=>setFilter("active")}>Pendentes</button><button className={filter==="mine"?"active":""} onClick={()=>setFilter("mine")}>Solicitadas por mim</button><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>Todas</button></div>
 <div className="workflow-grid">{visible.map(task=><article className="workflow-card" key={task.id}><header><div><small>{sourceLabel[task.source_type]||task.source_type} #{task.source_id}</small><h3>{task.title}</h3></div><span className={`driver-status ${task.status==="closed"?"ok":task.status==="returned"?"warning":""}`}>{statusLabel[task.status]||task.status}</span></header><p>{task.description||"Sem descrição complementar."}</p><dl><div><dt>Solicitante</dt><dd>{task.requester_name}</dd></div><div><dt>Setor atual</dt><dd>{task.current_department}</dd></div><div><dt>Responsável</dt><dd>{task.assignee_name||"Não atribuído"}</dd></div><div><dt>Situação de origem</dt><dd>{sourceStatusLabel[task.source_status||""]||task.source_status||"—"}</dd></div></dl><footer><button className="btn-ghost btn-mini" onClick={()=>open(task)}>Abrir trilha</button>{task.status==="open"&&<button className="btn-primary btn-mini" onClick={()=>start(task)}>Assumir</button>}</footer></article>)}{!visible.length&&<div className="empty-state">Nenhuma tarefa neste filtro.</div>}</div>
 {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="modal-card workflow-modal" onClick={e=>e.stopPropagation()}><h3>{selected.title}</h3><p>{selected.description}</p><div className="workflow-current"><span>Setor atual: <strong>{selected.current_department}</strong></span><span>Solicitante: <strong>{selected.requester_name}</strong></span></div>{selected.resolution&&<p className="workflow-resolution"><strong>Tratativa devolvida:</strong> {selected.resolution}</p>}<h4>Trilha de ações</h4><div className="workflow-history">{history.map(event=><div key={event.id}><time>{new Date(event.created_at).toLocaleString("pt-BR")}</time><strong>{eventLabel[event.action]||event.action.replaceAll("_"," ")}</strong><span>{event.actor_name||"Sistema"}{event.from_department&&event.to_department?` · ${event.from_department} → ${event.to_department}`:""}</span>{event.note&&<p>{translateTechnicalText(event.note)}</p>}</div>)}</div><div className="modal-actions">{!["returned","closed","cancelled"].includes(selected.status)&&<><button className="btn-ghost" onClick={()=>transfer(selected)}>Transferir setor</button><button className="btn-primary" onClick={()=>returnTask(selected)}>Devolver tratativa</button></>}{selected.status==="returned"&&selected.requester_id===user?.id&&<button className="btn-primary" onClick={()=>close(selected)}>Aceitar e finalizar</button>}<button className="btn-ghost" onClick={()=>setSelected(null)}>Fechar</button></div></div></div>}
 </div>
}
function translateTechnicalText(text:string){return text.replaceAll("approved","Aprovada").replaceAll("rejected","Recusada").replaceAll("pending","Pendente").replaceAll("in_review","Em análise").replaceAll("adjustment_requested","Ajuste solicitado").replaceAll("created","Criada").replaceAll("returned","Devolvida").replaceAll("closed","Finalizada")}
